services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/myapp
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  redis:
    image: redis:6-alpine
    volumes:
      - data_redis:/data
    ports:
      - "6380:6379"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    env_file:
      - .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    stdin_open: true
    tty: true

volumes:
  db_data:
  data_redis:
