name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:prepare
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed

      - name: Run RuboCop
        run: |
          bundle exec rubocop

      - name: Run RSpec
        run: |
          bundle exec rspec
